version: "3.6"

services:

    facerecon_api:
        image: facerecon_api
        build: .
        container_name: backend
        command: npm run start:dev
        working_dir: /usr/src/facerecon_api
        ports:
            - "3333:3333"
        env_file: .env
        volumes: 
            - ./:/usr/src/facerecon_api


    # We'll the heroku postgres databe instead
    # database:
    #     container_name: db
    #     restart: always
    #     build: database
    #     ports: 
    #         - "5555:5432"
    #     environment:
    #         POSTGRES_USER: gnarus
    #         POSTGRES_PASSWORD: pass
    #         POSTGRES_DB: facerecon
