version: "3.6"

services:

    facerecon_api:
        image: facerecon_api
        build: .
        container_name: backend
        command: npm run start:dev
        working_dir: /usr/src/facerecon_api
        ports:
            - "3333:3333"
        env_file: .env
        volumes: 
            - ./:/usr/src/facerecon_api

    redis:
        image: redis
        restart: always
        container_name: sessionDB
        ports: 
            - 6379:6379
